name: module3_task0

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  check-makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run make help
        run: |
          cd awesome-website
          make help


